# bandersnatch BitBucker Pipelines config to run Tox Tests
image: python:3.5.1

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - pip install .
          - tox
