# bandersnatch BitBucket pipelines config to run Tox tests
image: python:3

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - pip install tox
          - pip install .
          - tox
