#!/usr/bin/env python
import sys, os, shutil
import pep381client

if len(sys.argv) != 2:
    print "Usage: pep381run <targetdir>"
    raise SystemExit

targetdir = sys.argv[1]
if not os.path.exists(os.path.join(targetdir, 'web')):
    state = pep381client.Synchronization.initialize(targetdir)
else:
    state = pep381client.Synchronization.load(targetdir)

state.synchronize()
