name: bandersnatch_ci_latest

on: [push, pull_request]

jobs:
  build:
    name: bandersnatch CI python ${{ matrix.python-version }} on ${{matrix.os}}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10-dev]
    steps:
      - uses: actions/checkout@v2
      - uses: deadsnakes/action@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
          debug: true

      - name: Print Python Version
        run: python --version --version && which python

      - name: Install latest pip, setuptools + tox
        run: |
          python -m pip install --upgrade pip setuptools tox

      - name: Install dev dependency packages
        run: |
          apt install libxslt1-dev libxml2-dev

      - name: Install base bandersnatch requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Run Unittests
        env:
          SUPPRESS_ERRORS: 'True'
          TOXENV: py3
        run: |
          python test_runner.py

      - name: Run Integration Test
        env:
          SUPPRESS_ERRORS: 'True'
          TOXENV: INTEGRATION
        run: |
          python -m pip install .
          python test_runner.py
